import smtplib
import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
import io
import cv2
import numpy as np
from PIL import Image

def send_damage_report_email(
    smtp_server,
    smtp_port,
    sender_email,
    sender_password,
    receiver_email,
    damage_items,
    lat,
    lon,
    location_desc,
    image_input,  # numpy array (BGR or RGB) or PIL Image or bytes
    source_type="Image Detection"
):
    """
    Sends an HTML email report with the captured road damage photo, GPS location, and Google Maps link.
    """
    if not sender_email or not sender_password or not receiver_email:
        return False, "Missing SMTP email credentials. Please configure email settings in the sidebar or config."

    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        msg['Subject'] = f"🚨 Road Damage Alert [{source_type}]: {', '.join(set(damage_items))} Detected"

        maps_link = f"https://www.google.com/maps?q={lat},{lon}" if lat and lon else "#"
        lat_str = f"{lat:.6f}" if lat is not None else "N/A"
        lon_str = f"{lon:.6f}" if lon is not None else "N/A"

        damage_list_html = "".join([f"<li><strong>{item}</strong></li>" for item in damage_items])

        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
            <div style="background-color: #d9534f; color: white; padding: 15px; border-radius: 5px;">
                <h2 style="margin:0;">🚨 Road Damage Incident Notification</h2>
            </div>
            <div style="padding: 20px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 5px 5px;">
                <p>A new road damage incident has been captured and reported via the <strong>{source_type}</strong> application.</p>

                <h3>📌 Incident Details:</h3>
                <ul>
                    <li><strong>Timestamp:</strong> {timestamp_str}</li>
                    <li><strong>Detected Damage Types:</strong>
                        <ul>{damage_list_html}</ul>
                    </li>
                    <li><strong>Latitude:</strong> {lat_str}</li>
                    <li><strong>Longitude:</strong> {lon_str}</li>
                    <li><strong>Location Summary:</strong> {location_desc}</li>
                </ul>

                <p style="margin-top: 20px;">
                    <a href="{maps_link}" target="_blank" style="background-color: #0275d8; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; display: inline-block;">
                        📍 View Location on Google Maps
                    </a>
                </p>

                <h3>📷 Captured Photo:</h3>
                <p>The annotated photo showing the detected damage is attached to this email and displayed below:</p>
                <img src="cid:damage_image" style="max-width: 100%; border: 2px solid #ccc; border-radius: 5px;">
                
                <hr style="margin-top: 30px; border: None; border-top: 1px solid #eee;">
                <p style="font-size: 0.85em; color: #777;">Automated alert generated by Road Damage Detection System.</p>
            </div>
        </body>
        </html>
        """

        msg.attach(MIMEText(html_body, 'html'))

        # Prepare image attachment
        img_bytes = None
        if isinstance(image_input, np.ndarray):
            # Convert RGB/BGR array to PNG bytes
            if image_input.ndim == 3 and image_input.shape[2] == 3:
                # assuming RGB numpy array
                img_pil = Image.fromarray(image_input)
            else:
                img_pil = Image.fromarray(image_input)
            buf = io.BytesIO()
            img_pil.save(buf, format="PNG")
            img_bytes = buf.getvalue()
        elif isinstance(image_input, Image.Image):
            buf = io.BytesIO()
            image_input.save(buf, format="PNG")
            img_bytes = buf.getvalue()
        elif isinstance(image_input, bytes):
            img_bytes = image_input

        if img_bytes:
            img_mime = MIMEImage(img_bytes)
            img_mime.add_header('Content-ID', '<damage_image>')
            img_mime.add_header('Content-Disposition', 'inline', filename="road_damage_capture.png")
            msg.attach(img_mime)

        # Connect to SMTP server and send
        port = int(smtp_port) if smtp_port else 587
        with smtplib.SMTP(smtp_server, port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)

        return True, "Email notification sent successfully!"
    except Exception as e:
        return False, f"Failed to send email notification: {str(e)}"
